# Generated by Django 4.2.7 on 2023-11-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
